name: Hello world workflow 

on: 
  push: 
    branches: 
      - main
  pull_request: 
    branches:
      - main
  workflow_dispatch:

jobs: 
  hello: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2 
      - name: hello world 
        run: echo "Hello world 2"
        shell: bash 
  goobye: 
    runs-on: ubuntu-latest 
    steps: 
      - name: goodbye_world 
        run: echo "Goodbye world"
        shell: bash 

